extern alias JetBrains;
global using TheOtherRoles.Modules;
global using TheOtherRoles.Helper;
global using TheOtherRoles.Utilities;
global using TheOtherRoles.Utilities.Attribute;
global using Main = TheOtherRoles.TheOtherRolesPlugin;
global using UsedImplicitly = JetBrains::JetBrains.Annotations.UsedImplicitlyAttribute;
global using MeansImplicitUse = JetBrains::JetBrains.Annotations.MeansImplicitUseAttribute;
global using static TheOtherRoles.Helper.LogHelper;
global using static TheOtherRoles.Modules.LanguageExtension;