name: Auto Build Release

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - Release
  pull_request: 
    branches:
      - Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.x

      - name: install wget
        run: sudo apt install wget

      - name: download BepInEx
        run: wget https://builds.bepinex.dev/projects/bepinex_be/688/BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.688%2B4901521.zip

      - name: unzip BepInEx
        run: unzip BepInEx-Unity.IL2CPP-win-x86-6.0.0-be.688+4901521.zip -d ./Release/

      - name: path
        run: sudo chmod -R 777 ./Release

      - name: download Reactor
        run: wget https://github.com/NuclearPowered/Reactor/releases/latest/download/Reactor.dll -P ./Release/BepInEx/plugins

      - name: Build
        run: dotnet build TheOtherRoles/TheOtherRoles.csproj --configuration Release --output ./Release/BepInEx/plugins

      - name: Upload TheOtherUsDll
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TheOtherRoles.dll
          path: ./Release/BepInEx/plugins/TheOtherRoles.dll

      - name: Delete excess
        run: rm -rf ./Release/BepInEx/plugins/TheOtherRoles.deps.json ./Release/BepInEx/plugins/TheOtherRoles.pdb

      - name: Upload TheOtherUs
        uses: actions/upload-artifact@v4.3.1
        with:
          name: TheOtherUs
          path: ./Release/

